name: dp4imaging
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - pip
  - cpuonly
  - pip:
    - devito==4.6.2
    - h5py
    - matplotlib
    - numpy
    - tqdm
    - pandas
    - seaborn
    - GitPython
