name: dp4imaging
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - nvidia::cudatoolkit=11.3
  - python
  - pytorch::pytorch
  - pip
  - pip:
    - devito==4.6.2
    - h5py
    - matplotlib
    - numpy
    - tqdm
    - pandas
    - seaborn
    - GitPython
